export const SET_LOGIN_STATE = "SET_LOGIN_STATE"
export const SET_LOADED = 'SET_LOADED'
export const SET_USER_PROFILE = 'SET_USER_PROFILE'
export const SET_SIGNIN_PROFILE = 'SET_SIGNIN_PROFILE'
export const SET_STORE_OWNER = 'SET_SIGNIN_PROFILE'
export const SET_TOKEN = 'SET_TOKEN'
export const SET_PATH = 'SET_PATH'